import { Modal } from "antd";
import styles from "./createnewrunzmodal.module.css";
import Flex from "../../packages/Flex/Flex";
import Button from "../../packages/Button/Button";
import Text from "../../packages/Text/Text";
import SvgClose from "../../icons/SvgClose";
import SelectTag from "../../packages/SelectTag/SelectTag";
import InputText from "../../packages/InputText/InputText";
import SvgUnknown from "../../icons/SvgUnknown";

type Props = {
  open: boolean;
  cancelClick: () => void;
  suubmit: () => void;
};
const CreateNewRunzModal = ({ open, suubmit, cancelClick }: Props) => {
  return (
    <Modal
      width={900}
      onCancel={cancelClick}
      title={<Text type="title">Create new Assets</Text>}
      closeIcon={<SvgClose />}
      centered
      open={open}
      footer={
        <Flex row end center className={styles.footer}>
          <Button
            onClick={cancelClick}
            className={styles.cancelBtn}
            types="secondary"
          >
            Cancel
          </Button>
          <Button onClick={suubmit} className={styles.yesBtn}>
            Add
          </Button>
        </Flex>
      }
    >
      <Flex row between>
        <Flex column className={styles.leftModalContent}>
          <Flex className={styles.alignCenterMargin10}>
            <SvgUnknown height={200} width={200} />
          </Flex>

          <Flex row className={styles.overAll}>
            <Flex flex={1} className={styles.inputMarginRight20}>
              <InputText
                disabled
                value="IDAS304"
                label="Asset Id (autogenerated)"
              />
            </Flex>
          </Flex>

          <Flex>
            <Text size={16} bold="semiBold">
              Recently Used
            </Text>
          </Flex>

          <Flex className={styles.overAll}>
            <Text size={12} bold="semiBold">
              no data found
            </Text>
          </Flex>
        </Flex>

        <Flex column className={styles.rightModalContent}>
          <Flex className={styles.overAll}>
            <Flex row className={styles.inputFlexMargin}>
              <Flex flex={1} className={styles.inputMarginRight20}>
                <InputText placeholder="Assets name" label="Name" />
              </Flex>
            </Flex>

            <Flex row className={styles.inputMarginRight20}>
              <Flex flex={1} className={styles.inputMarginRight20}>
                <SelectTag options={[]} label="Purchase Date" />
              </Flex>
              <Flex flex={1}>
                <SelectTag options={[]} label="Guaranty/warranty/expiry date" />
              </Flex>
            </Flex>
            <Flex flex={1} className={styles.inputMarginRight20}>
              <SelectTag
                placeholder="Organisation"
                options={[]}
                label="Organisation"
                required
              />
            </Flex>
            <Flex flex={1} className={styles.inputMarginRight20}>
              <SelectTag
                placeholder="Department"
                options={[]}
                label="Departments"
                required
              />
            </Flex>

            <Flex flex={1} className={styles.inputMarginRight20}>
              <SelectTag
                placeholder="Select Lab"
                options={[]}
                label="Laboratory/ies"
                required
              />
            </Flex>

            <Flex row className={styles.inputMarginRight20}>
              <Flex flex={1} className={styles.inputMarginRight20}>
                <SelectTag
                  placeholder="Select Status"
                  options={[]}
                  label="status"
                />
              </Flex>
              <Flex flex={1}>
                <SelectTag
                  placeholder="Select Availability"
                  options={[]}
                  label="Availability"
                />
              </Flex>
            </Flex>
          </Flex>
        </Flex>
      </Flex>
    </Modal>
  );
};

export default CreateNewRunzModal;
