import { Modal } from "antd";
import Flex from "../../packages/Flex/Flex";
import styles from "./createoreditprocedure.module.css";
import SvgClose from "../../icons/SvgClose";
import Text from "../../packages/Text/Text";
import Button from "../../packages/Button/Button";
import InputText from "../../packages/InputText/InputText";
import DatePicker from "../../packages/DatePicker/DatePicker";

type Props = {
  cancelClick: () => void;
  open: boolean;
  submit: () => void;
  title: string;
};
const CreateOrEditProcedure = ({ cancelClick, open, submit, title }: Props) => {
  return (
    <Modal
      width={700}
      onCancel={cancelClick}
      title={<Text type="title">{title}</Text>}
      closeIcon={<SvgClose />}
      centered
      open={open}
      footer={
        <Flex row end center className={styles.footer}>
          <Button
            onClick={cancelClick}
            className={styles.cancelBtn}
            types="tertiary-1"
          >
            Create
          </Button>
          <Button onClick={submit} className={styles.yesBtn}>
            Create
          </Button>
        </Flex>
      }
    >
      <Flex className={styles.overAll}>
        <Flex row className={styles.inputFlexMargin}>
          <Flex flex={1} className={styles.inputMarginRight20}>
            <InputText disabled label="Procedure ID (autogenerated)" />
          </Flex>
          <Flex flex={1}>
            <DatePicker label="Created on" disabled />
          </Flex>
        </Flex>

        <Flex row className={styles.inputFlexMargin}>
          <Flex flex={1} className={styles.inputMarginRight20}>
            <InputText label="Department" />
          </Flex>
          <Flex flex={1}>
            <InputText label="Laboratory" />
          </Flex>
        </Flex>
        <Flex flex={1} className={styles.inputFlexMargin}>
          <InputText label="Procedure name" required />
        </Flex>
      </Flex>
    </Modal>
  );
};

export default CreateOrEditProcedure;
