import { Modal } from "antd";
import styles from "./createnewrunzmodal.module.css";
import Flex from "../../packages/Flex/Flex";
import Button from "../../packages/Button/Button";
import Text from "../../packages/Text/Text";
import SvgClose from "../../icons/SvgClose";
import SelectTag from "../../packages/SelectTag/SelectTag";
import InputText from "../../packages/InputText/InputText";

type Props = {
  open: boolean;
  cancelClick: () => void;
  submit: () => void;
  title: string;
  isEdit?: boolean;
};
const CreateNewRunzModal = ({
  open,
  submit,
  cancelClick,
  title,
  isEdit,
}: Props) => {
  return (
    <Modal
      width={700}
      onCancel={cancelClick}
      title={<Text type="title">{title}</Text>}
      closeIcon={<SvgClose />}
      centered
      open={open}
      footer={
        <Flex row end center className={styles.footer}>
          <Button
            onClick={cancelClick}
            className={styles.cancelBtn}
            types="tertiary-1"
          >
            Cancel
          </Button>
          <Button onClick={submit} className={styles.yesBtn}>
            {isEdit ? "Save" : "Create"}
          </Button>
        </Flex>
      }
    >
      <Flex className={styles.overAll}>
        {isEdit && (
          <>
            <Flex row className={styles.inputFlexMargin}>
              <Flex flex={1} className={styles.inputMarginRight20}>
                <SelectTag options={[]} label="Procedure ID (autogenerated)" />
              </Flex>
              <Flex flex={1}>
                <SelectTag options={[]} label="Created on" />
              </Flex>
            </Flex>
            <Flex row className={styles.inputFlexMargin}>
              <Flex flex={1} className={styles.inputMarginRight20}>
                <SelectTag options={[]} label="Department" required />
              </Flex>
              <Flex flex={1}>
                <SelectTag options={[]} label="Laboratory" />
              </Flex>
            </Flex>
          </>
        )}
        <Flex className={styles.inputFlexMargin}>
          <InputText label="Procedure name" />
        </Flex>
        <Flex flex={1} className={styles.inputFlexMargin}>
          <InputText label="Test objective" />
        </Flex>
        <Flex row className={styles.inputFlexMargin}>
          <Flex flex={1} className={styles.inputMarginRight20}>
            <InputText keyboardType="date" label="Set due date" />
          </Flex>
          <Flex flex={1}>
            <></>
          </Flex>
        </Flex>
      </Flex>
    </Modal>
  );
};

export default CreateNewRunzModal;
