export const ACTIVE_BACKING_BOARD: any = [
  {
    eventType: "Poker",
    eventName: "WSOP",
    amount: "$35.00",
    amountAvailable: "$35.00",
    time: "00 Days 10:22",
    potentialWin: "$1M",
    status: "Not Started",
    id: "1",
    name: "John Smith",
    winnings: "NA",
  },
  {
    eventType: "Poker",
    eventName: "Organization B",
    amount: "$35.00",
    amountAvailable: "$35.00",
    time: "00 Days 00:00 ",
    potentialWin: "$1M",
    status: "In progress",
    id: "2",
    name: "Elon Musk",
    winnings: "NA",
  },
  {
    eventType: "Poker",
    eventName: "Organization C",
    amount: "$1500.00",
    amountAvailable: "$1500.00",
    time: "Completed",
    potentialWin: "$1M",
    status: "Lost",
    id: "3",
    name: "Mike Angelo",
    winnings: "$0",
  },
  {
    eventType: "Poker",
    eventName: "Organization A",
    amount: "$165.00",
    amountAvailable: "$165.00",
    time: "Completed",
    potentialWin: "$500k",
    status: "Success",
    id: "4",
    name: "Sarah Whitmore",
    winnings: "$12,000",
  },
  {
    eventType: "Poker",
    eventName: "Organization B",
    amount: "$35.00",
    amountAvailable: "$35.00",
    time: "00 Days 00:00 ",
    potentialWin: "$1M",
    status: "In progress",
    id: "5",
    name: "Elon Musk",
    winnings: "NA",
  },
  {
    eventType: "Poker",
    eventName: "Organization C",
    amount: "$1500.00",
    amountAvailable: "$1500.00",
    time: "Completed",
    potentialWin: "$1M",
    status: "Lost",
    id: "6",
    name: "Mike Angelo",
    winnings: "$0",
  },
  {
    eventType: "Poker",
    eventName: "Organization A",
    amount: "$165.00",
    amountAvailable: "$165.00",
    time: "Completed",
    potentialWin: "$500k",
    status: "Success",
    id: "7",
    name: "Sarah Whitmore",
    winnings: "$12,000",
  },

  {
    eventType: "Poker",
    eventName: "Organization B",
    amount: "$35.00",
    amountAvailable: "$35.00",
    time: "00 Days 00:00 ",
    potentialWin: "$1M",
    status: "In progress",
    id: "8",
    name: "Elon Musk",
    winnings: "NA",
  },
  {
    eventType: "Poker",
    eventName: "Organization C",
    amount: "$1500.00",
    amountAvailable: "$1500.00",
    time: "Completed",
    potentialWin: "$1M",
    status: "Lost",
    id: "9",
    name: "Mike Angelo",
    winnings: "$0",
  },
  {
    eventType: "Poker",
    eventName: "Organization A",
    amount: "$165.00",
    amountAvailable: "$165.00",
    time: "Completed",
    potentialWin: "$500k",
    status: "Success",
    id: "10",
    name: "Sarah Whitmore",
    winnings: "$12,000",
  },

  {
    eventType: "Poker",
    eventName: "Organization B",
    amount: "$35.00",
    amountAvailable: "$35.00",
    time: "00 Days 00:00 ",
    potentialWin: "$1M",
    status: "In progress",
    id: "11",
    name: "Elon Musk",
    winnings: "NA",
  },
  {
    eventType: "Poker",
    eventName: "Organization C",
    amount: "$1500.00",
    amountAvailable: "$1500.00",
    time: "Completed",
    potentialWin: "$1M",
    status: "Lost",
    id: "12",
    name: "Mike Angelo",
    winnings: "$0",
  },
  {
    eventType: "Poker",
    eventName: "Organization A",
    amount: "$165.00",
    amountAvailable: "$165.00",
    time: "Completed",
    potentialWin: "$500k",
    status: "Success",
    id: "13",
    name: "Sarah Whitmore",
    winnings: "$12,000",
  },

  {
    eventType: "Poker",
    eventName: "Organization B",
    amount: "$35.00",
    amountAvailable: "$35.00",
    time: "00 Days 00:00 ",
    potentialWin: "$1M",
    status: "In progress",
    id: "14",
    name: "Elon Musk",
    winnings: "NA",
  },
  {
    eventType: "Poker",
    eventName: "Organization C",
    amount: "$1500.00",
    amountAvailable: "$1500.00",
    time: "Completed",
    potentialWin: "$1M",
    status: "Lost",
    id: "15",
    name: "Mike Angelo",
    winnings: "$0",
  },
  {
    eventType: "Poker",
    eventName: "Organization A",
    amount: "$165.00",
    amountAvailable: "$165.00",
    time: "Completed",
    potentialWin: "$500k",
    status: "Success",
    id: "16",
    name: "Sarah Whitmore",
    winnings: "$12,000",
  },

  {
    eventType: "Poker",
    eventName: "Organization B",
    amount: "$35.00",
    amountAvailable: "$35.00",
    time: "00 Days 00:00 ",
    potentialWin: "$1M",
    status: "In progress",
    id: "17",
    name: "Elon Musk",
    winnings: "NA",
  },
  {
    eventType: "Poker",
    eventName: "Organization C",
    amount: "$1500.00",
    amountAvailable: "$1500.00",
    time: "Completed",
    potentialWin: "$1M",
    status: "Lost",
    id: "18",
    name: "Mike Angelo",
    winnings: "$0",
  },
  {
    eventType: "Poker",
    eventName: "Organization A",
    amount: "$165.00",
    amountAvailable: "$165.00",
    time: "Completed",
    potentialWin: "$500k",
    status: "Success",
    id: "19",
    name: "Sarah Whitmore",
    winnings: "$12,000",
  },

  {
    eventType: "Poker",
    eventName: "Organization B",
    amount: "$35.00",
    amountAvailable: "$35.00",
    time: "00 Days 00:00 ",
    potentialWin: "$1M",
    status: "In progress",
    id: "20",
    name: "Elon Musk",
    winnings: "NA",
  },
  {
    eventType: "Poker",
    eventName: "Organization C",
    amount: "$1500.00",
    amountAvailable: "$1500.00",
    time: "Completed",
    potentialWin: "$1M",
    status: "Lost",
    id: "21",
    name: "Mike Angelo",
    winnings: "$0",
  },
  {
    eventType: "Poker",
    eventName: "Organization A",
    amount: "$165.00",
    amountAvailable: "$165.00",
    time: "Completed",
    potentialWin: "$500k",
    status: "Success",
    id: "22",
    name: "Sarah Whitmore",
    winnings: "$12,000",
  },

  {
    eventType: "Poker",
    eventName: "Organization B",
    amount: "$35.00",
    amountAvailable: "$35.00",
    time: "00 Days 00:00 ",
    potentialWin: "$1M",
    status: "In progress",
    id: "23",
    name: "Elon Musk",
    winnings: "NA",
  },
  {
    eventType: "Poker",
    eventName: "Organization C",
    amount: "$1500.00",
    amountAvailable: "$1500.00",
    time: "Completed",
    potentialWin: "$1M",
    status: "Lost",
    id: "24",
    name: "Mike Angelo",
    winnings: "$0",
  },
  {
    eventType: "Poker",
    eventName: "Organization A",
    amount: "$165.00",
    amountAvailable: "$165.00",
    time: "Completed",
    potentialWin: "$500k",
    status: "Success",
    id: "25",
    name: "Sarah Whitmore",
    winnings: "$12,000",
  },

  {
    eventType: "Poker",
    eventName: "Organization B",
    amount: "$35.00",
    amountAvailable: "$35.00",
    time: "00 Days 00:00 ",
    potentialWin: "$1M",
    status: "In progress",
    id: "26",
    name: "Elon Musk",
    winnings: "NA",
  },
  {
    eventType: "Poker",
    eventName: "Organization C",
    amount: "$1500.00",
    amountAvailable: "$1500.00",
    time: "Completed",
    potentialWin: "$1M",
    status: "Lost",
    id: "27",
    name: "Mike Angelo",
    winnings: "$0",
  },
  {
    eventType: "Poker",
    eventName: "Organization A",
    amount: "$165.00",
    amountAvailable: "$165.00",
    time: "Completed",
    potentialWin: "$500k",
    status: "Success",
    id: "28",
    name: "Sarah Whitmore",
    winnings: "$12,000",
  },

  {
    eventType: "Poker",
    eventName: "Organization B",
    amount: "$35.00",
    amountAvailable: "$35.00",
    time: "00 Days 00:00 ",
    potentialWin: "$1M",
    status: "In progress",
    id: "29",
    name: "Elon Musk",
    winnings: "NA",
  },
  {
    eventType: "Poker",
    eventName: "Organization C",
    amount: "$1500.00",
    amountAvailable: "$1500.00",
    time: "Completed",
    potentialWin: "$1M",
    status: "Lost",
    id: "30",
    name: "Mike Angelo",
    winnings: "$0",
  },
  {
    eventType: "Poker",
    eventName: "Organization A",
    amount: "$165.00",
    amountAvailable: "$165.00",
    time: "Completed",
    potentialWin: "$500k",
    status: "Success",
    id: "31",
    name: "Sarah Whitmore",
    winnings: "$12,000",
  },
];

export const activeBackingBoard = () => [
  {
    title: "Event Type",
    dataIndex: "eventType",
    key: "eventType",
  },
  {
    title: "Event Name",
    dataIndex: "eventName",
    key: "eventName",
    flex: 1.5,
  },
  {
    title: "Amount Backed",
    dataIndex: "amount",
    key: "amount",
  },
  {
    title: "Backing Amount Available",
    dataIndex: "amountAvailable",
    key: "amountAvailable",
  },
  {
    title: "Time Remaining",
    dataIndex: "time",
    key: "time",
  },
  {
    title: "Potential Win",
    dataIndex: "potentialWin",
    key: "potentialWin",
  },
  {
    title: "Winnings",
    dataIndex: "winnings",
    key: "winnings",
  },
  {
    title: "Status",
    dataIndex: "status",
    key: "status",
    align: "center",
  },
];

export const activeBackingHeader = () => [
  {
    title: "Name",
    dataIndex: "name",
    key: "name",
  },
  {
    title: "Time Remaining",
    dataIndex: "time",
    key: "time",
    align: "center",
  },
  {
    title: "Role",
    dataIndex: "role",
    key: "role",
    align: "center",
  },
  {
    title: "Status",
    dataIndex: "status",
    key: "status",
    align: "center",
  },
];

export const ACTIVE_USER_DATA: any = [
  {
    time: "00 Days 10:22",
    status: "Not Started",
    id: "1",
    name: "John Smith",
    role: "Admin"
  },
  {
    time: "00 Days 10:22",
    status: "Not Started",
    id: "2",
    name: "John Worth",
    role: "Admin"
  },
];
